### ISSUE TITLE
ForkするとgithubからCNAMEに関しての警告メールが届く

### ISSUE THREAD

**Issue by ohac** [visvirial/OfflineWallet#4]
特に問題はないと思いますが、Forkする人が増えると問い合わせも増えるような気がしますのでIssueにしておきます。
下記のようなメールが届きました。

The page build completed successfully, but returned the following warning:

CNAME already taken: offlinewallet.info

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

**Comment by visvirial** [comment]
どうすればこちらの警告が届かなくなるか分かりますでしょうか？

**Comment by ohac** [comment]
ちょっと調べてみましたが、他の例で対処法みたいなのはなさそうなので、これはどうしようもなさそうですね。
Forkした人にとってはCNAMEファイルを書き換えないといけない、ということがわかるので、これはこのままでもよいのかもしれません。
一応、お知らせしておきたかっただけなので、とりあえず閉じておきます。
