### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by ohac** [visvirial/OfflineWallet#5]
提案です。
プロジェクトの設定でEnforce HTTPSというのがあるのですが、これをONにするのはいかがでしょうか。

**Comment by visvirial** [comment]
![options](https://cloud.githubusercontent.com/assets/6349067/15919827/e4d2121c-2e4f-11e6-8196-5651371c0883.png)

残念ながら利用できないようです。

**Comment by ohac** [comment]
なるほど。独自ドメインではだめなのですね。
検討ありがとうございます。
